Models/ModelsView/PersonView.cs
using Directory.Models.Identity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Directory.Models.ModelsView
{
	public class PersonView
	{
		public string Id { get; set; }

		[DataType(DataType.Text)]
		[Required(ErrorMessage = "Поле является обязательным к заполнению")]
		[Display(Name = "Имя")]
		public string FirstName { get; set; }

		[DataType(DataType.Text)]
		[Required(ErrorMessage = "Поле является обязательным к заполнению")]
		[Display(Name = "Фамилия")]
		public string LastName { get; set; }

		[DataType(DataType.Text)]
		[Display(Name = "Отчество")]
		public string MiddleName { get; set; }

		//[DataType(DataType.Text)]
		//[Required(ErrorMessage = "Поле является обязательным к заполнению")]
		//[Display(Name = "Логин")]
		//public string UserName { get; set; }

		[DataType(DataType.Password)]
		[Display(Name = "Пароль")]
		public string Password { get; set; }

		[DataType(DataType.PhoneNumber)]
		[Display(Name = "Телефон")]
		public string PhoneNumber { get; set; }

		[DataType(DataType.Text)]
		[Required(ErrorMessage = "Поле является обязательным к заполнению")]
		[Display(Name = "Название системы")]
		public string NameSystem { get; set; }

		[EmailAddress]
		[Required(ErrorMessage = "Поле является обязательным к заполнению")]
		[Display(Name = "Эл. Почта")]
		public string Email { get; set; }

		[DataType(DataType.Text)]
		[Required(ErrorMessage = "Поле является обязательным к заполнению")]
		[Display(Name = "Обоснование")]
		public string Grounding { get; set; }

		[Display(Name = "Права (роль) пользователя")]
		public List<Role> RoleId { get; set; }

		[Display(Name = "Заблокирован")]
		public bool LockoutEnabled { get; set; }

		[Display(Name = "Это Анкета")]
		public bool isApplicationForm { get; set; }

		public PersonView()
		{
			RoleId = new List<Role>();
		}
	}
}

Controllers/PersonController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using Directory.Models.Filters;
using Directory.Services;
using Directory;
using Directory.Services.interfaces;
using Directory.Models.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Directory.framework;
using Newtonsoft.Json;
using Directory.Data.Common;
using Directory.Models.ModelsView;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Directory.Mails;
using Microsoft.Extensions.Logging;

namespace testMVC.Controllers
{
	[Authorize(Roles = "Администратор")]
	public class PersonController : JsonController
	{
		private readonly ILogger<PersonController> _logger;
		private readonly UserManager<Person> _userManager;
		private readonly IPersonServices _personServices;
		private readonly IMapper _mapper;
		private readonly IUnitOfWorkFactory _unitOfWorkFactory;
		private ITokenServices _token;

		public PersonController(
			ILogger<PersonController> logger,
			UserManager<Person> userManager,
			IPersonServices personServices,
			IMapper mapper,
			IUnitOfWorkFactory unitOfWorkFactory,
			ITokenServices token)
		{
			_logger = logger;
			_userManager = userManager;
			_personServices = personServices;
			_mapper = mapper;
			_unitOfWorkFactory = unitOfWorkFactory;
			_token = token;
		}

		[Route("Person/{id?}/{firstName?}/{lastName?}/{userName?}")]
		public ActionResult Index(PersonFilter filter)
		{
			if (filter is null) { throw new ArgumentNullException("filter is null", nameof(filter)); }

			_logger.LogInformation($"Пользователи: Выдача данных");

			try
			{
				var persons = _personServices.FilterPerson(filter);

				//Показываю сначало заявки, потом пользователей незаблокированных, после всех остальных
				filter.persons = persons.OrderBy(loc => loc.LockoutEnabled == true).OrderBy(e => e.isApplicationForm == false).ToList();

				return View(filter);
			}
			//При ошибки может быть дисконект с сервером и тд
			catch (ArgumentOutOfRangeException e) { ViewBag.BadRequestMessage = e.Message; return View("BadRequest"); }
			catch (Exception e) { return StatusCode(500, e.Message); }

		}
		public ActionResult Details(int id)
		{
			return View();
		}

		[AllowAnonymous]
		[Route("Person/Create/")]
		[HttpGet]
		public IActionResult Create()
		{
			_logger.LogInformation($"Пользователи: попытка создания нового и заполнение анкеты");

			return View();
		}

		[AllowAnonymous]
		[Route("Person/Save")]
		[HttpPost]
		public async Task<ActionResult> Save(PersonView createPers)
		{
			try
			{
				if (createPers is null) { ModelState.AddModelError("Name", "Профиль пустой"); }

				if (createPers.FirstName.Where(let => !char.IsLetter(let)).Count() > 0 || createPers.FirstName.Length > 25) { ModelState.AddModelError("Name", "Некорректное имя"); }

				if (createPers.LastName.Where(let => !char.IsLetter(let)).Count() > 0 || createPers.LastName.Length > 30) { ModelState.AddModelError("LastName", "Некорректная фамилия"); }

				if (!string.IsNullOrEmpty(createPers.MiddleName))
				{
					if (createPers.MiddleName.Where(let => !char.IsLetter(let)).Count() > 0 || createPers.MiddleName.Length > 30) { ModelState.AddModelError("MiddleName", "Некорректное отчество"); }
				}

				if (createPers.NameSystem.Length > 40) { ModelState.AddModelError("NameSystem", "Название системы слишком длинное"); }

				if (createPers.PhoneNumber.Where(let => !char.IsDigit(let)).Count() > 0 || createPers.PhoneNumber.Length > 30 || createPers.PhoneNumber.Length < 6) { ModelState.AddModelError("PhoneNumber", "Некорректный номер телефона, можно использовать только цифры"); }

				if (createPers.Grounding.Length > 255) { ModelState.AddModelError("Grounding", "Обоснование слишком длинное"); }

				if (ModelState.IsValid)
				{

					//Получаю доступные роли
					List<PersonRole> GetUserRoles()
					{
						var userRoles = new List<PersonRole>();

						foreach (var role in createPers.RoleId)
						{
							userRoles.Add(new PersonRole { RoleId = role.Id });
						}

						return userRoles;
					}
					//Если пользователь еще не создан, синхронизируем его с ролью и добавляем
					if (createPers.Id == null)
					{

						Person persModels = new()
						{
							PersonRole = GetUserRoles()
						};

						string id = persModels.Id;

						persModels = _mapper.Map<Person>(createPers);

						persModels.Id = id;

						//Нам вообще не нужен UserName но Web API не создает без него данные
						persModels.UserName = id;	

						_token = new TokenServices(_unitOfWorkFactory);

						//Создаем токин и заполняем его индекс.
						persModels.TokenId = _token.CreateToken(id);

						await _userManager.CreateAsync(persModels);
						await _userManager.SetLockoutEnabledAsync(persModels, false);

						//Текст сообщения может измениться, исходя от того, одобрили ли заявку
						string message = ""; string pass = "";

						pass = GetPassword(12).Password;
						await _userManager.AddPasswordAsync(persModels, pass);
						message = $"Пользователь успешно активирован для медицинских справочников.\nВам выдан токен, через который вы можете получить данные любого справочника, через API на сайте.\n Ваш токен: {_token.GetTokenById(persModels.TokenId).Tokens}";

						//Отправляется сообщение пользователю
						new Mail("minzdravkr@mail.ru").Send("rnaXB5EqBW7tBhJttav7", new Mail(persModels.Email), message, "Данные для входа");

						_logger.LogInformation($"Пользователи: создание анкеты и пользователя {createPers.Id}");

					}
					//Если создан, то обновляем пользователя
					else
					{
						Person user = await _userManager.Users.Include(u => u.PersonRole).SingleOrDefaultAsync(u => u.Id == createPers.Id);

						user.LastName = createPers.LastName;
						user.FirstName = createPers.FirstName;
						user.Email = createPers.Email;
						user.Grounding = createPers.Grounding;
						user.MiddleName = createPers.MiddleName;
						user.PhoneNumber = createPers.PhoneNumber;
						user.PersonRole = GetUserRoles();

						if (createPers.LockoutEnabled) { await BlockUser(user.Id); } else { await ActivateUser(user.Id); }

						await _userManager.UpdateAsync(user);

						_logger.LogInformation($"Пользователи: Редактирование пользователя или анкеты {createPers.Id}");

					}
				}

			}
			//При ошибки может быть дисконект с сервером и тд
			catch (ArgumentOutOfRangeException e) { ViewBag.BadRequestMessage = e.Message; return RedirectToAction("Home", "Error"); }
			catch (Exception e) { return StatusCode(500, e.Message); }

			if (ModelState.IsValid) { return RedirectToAction("Index", "Home"); }
			else { ViewBag.BadRequestMessage = ModelState.Values; return View("Create"); }

		}

		[Route("Person/Edit/{id?}")]
		public ActionResult Edit(string id)
		{
			if (string.IsNullOrWhiteSpace(id))
			{
				ModelState.AddModelError("Invalid SectionName", $"*Айди обязательно!");

				ViewBag.BadRequestMessage = "Person id is NULL";

				return View("Edit", id);
			}

			_logger.LogInformation($"Пользователи: Редактирование пользователя {id}");

			return View(_personServices.GetPersonById(id));
		}

		[Route("Person/InfoPerson/{id}")]
		public ActionResult InfoPerson(string id)
		{
			_logger.LogInformation($"Пользователи: Подробности пользователя {id}");

			return View(_personServices.GetPersonById(id));
		}

		[Route("Person/ResetPassword/{userId}")]
		public async Task<IActionResult> ResetPassword(string userId)
		{
			if (string.IsNullOrWhiteSpace(userId))
			{
				ModelState.AddModelError("Invalid SectionName", $"*Айди обязательно!");

				ViewBag.BadRequestMessage = "Person id is NULL";

				return View("Edit", userId);
			}

			_logger.LogInformation($"Пользователи: сброс пароля пользователя: {userId}");

			if (userId != null)
			{
				string pass = GetPassword(12).Password;

				await _personServices.ResetPassword(userId, pass);

				TempData["AlertResult"] = JsonConvert.SerializeObject(Result.Failure($"Пароль успешно обновлен до {pass}"));
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		public async Task<IActionResult> BlockUser(string userId)
		{
			if (userId == null)
				return Ok("Ошибка: не удалось выполнить действие");

			_logger.LogInformation($"Пользователи: блокировка пользователя: {userId}");

			var tokenByPerson = _token.GetTokenByPersonId(userId);

			await _personServices.BlockUser(userId);

			tokenByPerson._dateEnd = DateTime.Now;

			_token.EditToken(tokenByPerson);

			return Ok("Пользователь успешно заблокирован!");
		}

		[HttpPost]
		public async Task<IActionResult> ActivateUser(string userId)
		{
			if (userId == null)
				return Ok("Ошибка: не удалось выполнить действие");

			_logger.LogInformation($"Пользователи: активация пользователя: {userId}");

			await _personServices.ActivateUser(userId);

			var tokenByPerson = _token.GetTokenByPersonId(userId);

			tokenByPerson._dateEnd = new DateTime();

			_token.EditToken(tokenByPerson);

			return Ok("Пользователь успешно разблокирован!");
		}


		#region "Внутренние функции"

		///<summary>Проверяю пароль на прочность</summary>
		///<param name="length">Длина пароля</param>
		private static (string Password, int[] CharsCount) GetPassword(int length)
		{
			if (length <= 0) { throw new ArgumentOutOfRangeException(nameof(length), "Длина пароля не может быть представлена отрицательным числом или нулем."); }

			Random rnd = new Random();

			char[][] chars = {
			new char[] { 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z' },
			new char[] { 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z' },
			new char[] { '0','1','2','3','4','5','6','7','8','9' },
			new char[] { '~', '!', '?', '[', ']', '(', ')', '{', '}', '@', '#', '$', '%', '&', '*', '^' }};

		generatePassword:
			string password = "";
			int[] charsCount = new int[chars.Length];

Views/Person/Create.cshtml
@model Directory.Models.ModelsView.PersonView

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Создание пользователя</h1>

<h4>Пользователь</h4>
<hr />
<div class="row" >
    <div class="col-md-4">
        <form asp-action="Save" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" placeholder="mail@gmail.com" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameSystem" class="control-label"></label>
                <input asp-for="NameSystem" class="form-control" />
                <span asp-validation-for="NameSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" placeholder="996 (999) 99-99-99" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grounding" class="control-label"></label>
                <input asp-for="Grounding" class="form-control">
                <span asp-validation-for="Grounding" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться обратно</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Person/Edit.cshtml
@model Directory.Models.ModelsView.PersonView

<h4>Пользователь @Model.LastName</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Save">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameSystem" class="control-label"></label>
                <input asp-for="NameSystem" class="form-control" />
                <span asp-validation-for="NameSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grounding" class="control-label"></label>
                <p><textarea asp-for="Grounding" maxlength="255" class="form-control-grounding"></textarea></p>
                <span asp-validation-for="Grounding" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LockoutEnabled" class="control-label"></label>
                <input type="checkbox" asp-for="LockoutEnabled" class="form-control" />
                <span asp-validation-for="LockoutEnabled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
            <div style="padding: 12px 0px 12px 0px;">
                <a class="next-little font-size-base d-none d-md-inline mr-3" asp-controller="Person" asp-action="ResetPassword" asp-route-id="@Model.Id">Сбросить пароль</a>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Вернуться обратно</a>
</div>

Views/Person/Index.cshtml
@model Directory.Models.Filters.PersonFilter
@{
    ViewData["Title"] = "Persons";
}

<h1>Пользователи</h1>

<div class="row" >
    <div class="col-md-12">
        <form asp-action="Index" method="get">
            <div class="col-md-12">
                <div class="container" style="margin-top: 50px;">
                    <div class="row">
                        <div  class="col-3">
                            <label asp-for="FirstName" class="control-label">Имя</label>
                            <input asp-for="FirstName" class="form-control" value="@Model.FirstName" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="col-3">
                            <label asp-for="LastName" class="control-label">Фамилия</label>
                            <input asp-for="LastName" class="form-control" value="@Model.LastName" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="col-3" style="margin-top:32px;">
                            <input type="submit" value="Поиск" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div style="cursor: pointer; margin: 20px;">
        <a class="next" asp-controller="Person" asp-action="Create">Создать нового</a>
    </div>
</div>

<table class="table">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.persons.First().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.persons.First().LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.persons.First().MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.persons.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.persons.First().PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.persons.First().LockoutEnabled)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model.persons)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => person.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => person.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => person.MiddleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => person.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => person.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => person.LockoutEnabled)
                </td>
                @if (User.IsInRole("Администратор"))
                {
                    <td>
                        <div class="navbar-nav" style="cursor: pointer;">
                            <div class="dropdown">
                                <div id="dropdownMenuButton">
                                    <a class="next-little font-size-base d-none d-md-inline mr-3" asp-controller="Person" asp-action="Edit" asp-route-id="@person.Id">Редактировать</a>
                                </div>
                            </div>
                        </div>
                        <div>
                            <a class="next-little font-size-base d-none d-md-inline mr-3" asp-controller="Person" asp-action="InfoPerson" asp-route-id="@person.Id">Подробней</a>
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Views/Person/InfoPerson.cshtml
@model Directory.Models.ModelsView.PersonView

@{
    ViewData["Title"] = "InfoPerson";
}

<h1>Информация о пользователе @Model.LastName</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Grounding)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Grounding)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>
    </dl>
</div>

<div>
    <a style="padding: 10px" asp-action="Index">Вернуться обратно</a>
</div>